---
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - name: remove trailing whitespace
        id: trailing-whitespace
      - name: add newline to end of files
        id: end-of-file-fixer
      - name: sort requirements.txt
        id: requirements-txt-fixer

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - name: sort python imports
        id: isort

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - name: format python files
        id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - name: check python syntax
        id: flake8

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.18
    hooks:
      - name: format Markdown files
        id: mdformat
        args:
          - --wrap=88
          - --end-of-line=keep
        additional_dependencies:
          - mdformat-gfm
